name: Lint Check (pre-commit)

on:
  # We have to use pull_request_target here as pull_request does not grant
  # enough permission for reviewdog
  pull_request_target:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-pre-commit.yml@aff2108f4f48fd423d2f1e9d3cf7dae9f46112fe # ratchet:bemanproject/infra-workflows/.github/workflows/reusable-beman-pre-commit.yml@1.6.0
