# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Makefile Workflow Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'

jobs:
  test_matrix:
    strategy:
      fail-fast: false
    name:  Test System Compiler with Makefile
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/bemanproject/testingcontainers-gcc:14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.11.6"
      - name: Install gcc
        shell: bash
        run: |
         sudo apt update
         sudo apt -y install build-essential g++-14

      - name: Configure Environment
        shell: bash
        run: |
          make venv

        env:
          CMAKE_GENERATOR: "Ninja Multi-Config"
      - name: Build
        shell: bash
        run: |
         source .venv/bin/activate
         make compile
      - name: Test
        shell: bash
        run: |
         source .venv/bin/activate
         make test
      - name: Generate Coverage Files
        shell: bash
        run: |
         source .venv/bin/activate
         make coverage
      - name: Lint
        shell: bash
        run: |
         source .venv/bin/activate
         make lint
      - name: Manual Lint
        shell: bash
        run: |
         source .venv/bin/activate
         make lint
      - name: Test Install
        shell: bash
        run: |
         source .venv/bin/activate
         make testinstall
